exports = [
  "Bla bla?",
  "Bla! Bla!",
  "Heee...",
  "Was denn?",
  "Dum di du",
  "Papperlapapp",
  "Blupp",
  "Grrr...",
  "Schuwidu...",
  "Bli bla blup",
  "Schoko...",
  "...bons",
  "Durchbrennen?",
  "Ich lass den ",
  "Wagen an!",
  "Und jetzt?",
  "Chillen!",
  "Schlafen!",
  "Okee...",
  "Herrjeminee",
  "Fraujeminee",
  "Mr...",
  "Mrs...",
  "Bart...",
  "...bruder",
  "Bier!",
  "Cola!",
  "Hilfe!",
  "Keine Sorge!",
  "Was zum...",
  "...Kuckuck?",
  "Da ham wa...",
  "... den Salat...",
  "Oh neeein!",
  "Hae?",
  "Hrm...",
  "Ker, ker, ker...",
  "Nicht denk...",
  "Denk...",
  "Na sowas?!",
  "Was zum?",
  "Bomben und",
  "Granaten!",
  "Himmel, Arsch,",
  "und Zwirn!",
  "ToeTo...",
  "ToeoeoeM!",
  "Schokolade?",
  "Kaaaaffeeee!",
  "Urlaub",
  "Muede",
  "Grummelig",
  "Happy",
  "Spieleabend?",
  "Pause",
  "Soft Cake",
  "Auszeit",
  "Außer Betrieb",
  "Error",
  "Rechne mal kurz",
  "Spazieren?",
  "Gammeln",
  "Essen",
  "Waaasssrr",
  "Depeche Mode",
  "Gehirnstarre",
  "Wtf?",
  "LOL",
  "Boooom",
  "Ja ich… sehe es",
  "Haensel",
  "Bist du naerrisch?",
  "O-Kaese",
  "Gras",
  "Nein",
  "Ja",
  "Willst du…",
  "Vielleicht",
  "Lieber nicht",
  "Morgen",
  "Gestern",
  "Zu spaet",
  "Noch nicht",
  "Aber, aber",
  "Scheusslich",
  "Piieeep",
];
