exports = {
    rickroll: {
        width : 50, height : 50, bpp : 1,
        buffer : atob("AAPz8PAAAAD8/DwAA/8wPw8/8P/MD8PP/DAzP/zzAwwMz/88wMMDPPw/MDDAzz8PzAwwMwMM8wMMDMDDPMDD/zMwAz/w/8zMAM/8AAMzMzAAAADMzMwAD//zDw/////8w8P//wzw/MMwMMM8PzDMDDDw/MAwP/A8PzAMD/wwA///zzwMAP//888M/8AM/A//P/ADPwP//AMzAwDMPwDMwMAzDwz/8z8MM8M//M/DDDzD/DMwMw8w/wzMDMwAwMzz888AMDM8/PMMMMz8AAPDDDM/AAD///Mww/Dz//zMMPw8AAMDzDMMAADA8wzDA/888wPwDP/PPMD8AzAzwA8AD8wM8APAA/MDMPM/wDzAzDzP8A8wM//AzDMMDP/wMwzD/zAA8Pz8/8wAPD8/AAM//DD8AADP/ww/AA==")
    },
    hearts: {
        width : 64, height : 64, bpp : 1,
        buffer : atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAQAAAAAAf8Af8AAAAAH/4H/4AAAAA//w//wAAAAD//j//gAAAAf//f/+AAAAB//9//8AAAAH/////wAAAAf/////AAAAB/////8AAAAH/////wAAAAf/////AAAAB/////8AAAAH/////gAAAAP////+AAAAA/////4AAAAB/////AAAAAH////4AAAAAP////gAAAAAf///8AAAAAB////gAAAAAD///+AAAAAAH///wAAAAAAP//+AAAAAAA///wAAAAAAB///A/AfgAAD//4H/D/gAAH//A/+f+AAAf/4H/7/8AAA//gf///wAAB/8B////AAAH/gH///8AAAP+Af///wAAAfwB////AAAB/AH///8AAAD4AP///gAAAPgA///+AAAAcAB///wAAABwAD///AAAAGAAH//4AAAAIAAf//AAAAAAAA//4AAAAAAAB//gAAAAAAAD/8AAAAAAAAP/gAAAAAAAAf8AAAAAAAAA/wAAAAAAAAD+AAAAAAAAAH4AAAAAAAAAfAAAAAAAAAA4AAAAAAAAADgAAAAAAAAAGAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=")
    }
};